name: Ignacio Galdames
url: http://ignaciogaldames.com
markdown: kramdown
kramdown:
  entity_output: :as_input
permalink: pretty

collections:
  cuentos:
    output: true
  libros:
    output: true

plugins_dir:
  - jekyll-sitemap

source: _source
timezone: America/Santiago